export const initialText = `For a long time I would go to bed early. Sometimes, the candle barely out, my eyes closed so quickly that I did not have time to tell myself: “I’m falling asleep.” And half an hour later the thought that it was time to look for sleep would `;

export const allText = `For a long time I would go to bed early. Sometimes, the candle barely out, my eyes closed so quickly that I did not have time to tell myself: “I’m falling asleep.” And half an hour later the thought that it was time to look for sleep would awaken me; I would make as if to put away the book which I imagined was still in my hands, and to blow out the light; I had gone on thinking, while I was asleep, about what I had just been reading, but these thoughts had taken a rather peculiar turn; it seemed to me that I myself was the immediate subject of my book: a church, a quartet, the rivalry between François I and Charles V. This impression would persist for some moments after I awoke; it did not offend my reason, but lay like scales upon my eyes and prevented them from registering the fact that the candle was no longer burning. Then it would begin to seem unintelligible, as the thoughts of a previous existence must be after reincarnation; the subject of my book would separate itself from me, leaving me free to apply myself to it or not; and at the same time my sight would return and I would be astonished to find myself in a state of darkness, pleasant and restful enough for my eyes, but even more, perhaps, for my mind, to which it appeared incomprehensible, without a cause, something dark indeed.

I would ask myself what time it could be; I could hear the whistling of trains, which, now nearer and now further off, punctuating the distance like the note of a bird in a forest, showed me in perspective the deserted countryside through which a traveller is hurrying towards the nearby station; and the path he is taking will be engraved in his memory by the excitement induced by strange surroundings, by unaccustomed activities, by the conversation he has had and the farewells exchanged beneath an unfamiliar lamp that still echo in his ears amid the silence of the night, and by the happy prospect of being home again.

I would lay my cheeks gently against the comfortable cheeks of my pillow, as plump and fresh as the cheeks of childhood. I would strike a match to look at my watch. Nearly midnight. The hour when an invalid, who has been obliged to set out on a journey and to sleep in a strange hotel, awakened by a sudden spasm, sees with glad relief a streak of daylight showing under his door. Thank God, it is morning! The servants will be about in a minute: he can ring, and someone will come to look after him. The thought of being assuaged gives him strength to endure his pain. He is certain he heard footsteps: they come nearer, and then die away. The ray of light beneath his door is extinguished. It is midnight; someone has just turned down the gas; the last servant has gone to bed, and he must lie all night suffering without remedy.

I would fall asleep again, and thereafter would reawaken for short snatches only, just long enough to hear the regular creaking of the wainscot, or to open my eyes to stare at the shifting kaleidoscope of the darkness, to savour, in a momentary glimmer of consciousness, the sleep which lay heavy upon the furniture, the room, that whole of which I formed no more than a small part and whose insensibility I should very soon return to share. Or else while sleeping I had drifted back to an earlier stage in my life, now for ever outgrown, and had come under the thrall of one of my childish terrors, such as that old terror of my great-uncle’s pulling my curls which was effectually dispelled on the day—the dawn of a new era to me—when they were finally cropped from my head. I had forgotten that event during my sleep, but I remembered it again immediately I had succeeded in waking myself up to escape my great-uncle’s fingers, and as a measure of precaution I would bury the whole of my head in the pillow before returning to the world of dreams.

Sometimes, too, as Eve was created from a rib of Adam, a woman would be born during my sleep from some misplacing of my thigh. Conceived from the pleasure I was on the point of enjoying, she it was, I imagined, who offered me that pleasure. My body, conscious that its own warmth was permeating hers, would strive to become one with her, and I would awake. The rest of humanity seemed very remote in comparison with this woman whose company I had left but a moment ago; my cheek was still warm from her kiss, my body ached beneath the weight of hers. If, as would sometimes happen, she had the features of some woman whom I had known in waking hours, I would abandon myself altogether to this end: to find her again, like people who set out on a journey to see with their eyes some city of their desire, and imagine that one can taste in reality what has charmed one’s fancy. And then, gradually, the memory of her would fade away, I had forgotten the girl of my dream.`;

export const paragraphs = [
  `For a long time I would go to bed early. Sometimes, the candle barely out, my eyes closed so quickly that I did not have time to tell myself: “I’m falling asleep.” And half an hour later the thought that it was time to look for sleep would awaken me; I would make as if to put away the book which I imagined was still in my hands, and to blow out the light; I had gone on thinking, while I was asleep, about what I had just been reading, but these thoughts had taken a rather peculiar turn; it seemed to me that I myself was the immediate subject of my book: a church, a quartet, the rivalry between François I and Charles V. This impression would persist for some moments after I awoke; it did not offend my reason, but lay like scales upon my eyes and prevented them from registering the fact that the candle was no longer burning. Then it would begin to seem unintelligible, as the thoughts of a previous existence must be after reincarnation; the subject of my book would separate itself from me, leaving me free to apply myself to it or not; and at the same time my sight would return and I would be astonished to find myself in a state of darkness, pleasant and restful enough for my eyes, but even more, perhaps, for my mind, to which it appeared incomprehensible, without a cause, something dark indeed.`,
  `I would ask myself what time it could be; I could hear the whistling of trains, which, now nearer and now further off, punctuating the distance like the note of a bird in a forest, showed me in perspective the deserted countryside through which a traveller is hurrying towards the nearby station; and the path he is taking will be engraved in his memory by the excitement induced by strange surroundings, by unaccustomed activities, by the conversation he has had and the farewells exchanged beneath an unfamiliar lamp that still echo in his ears amid the silence of the night, and by the happy prospect of being home again.`,
  `I would lay my cheeks gently against the comfortable cheeks of my pillow, as plump and fresh as the cheeks of childhood. I would strike a match to look at my watch. Nearly midnight. The hour when an invalid, who has been obliged to set out on a journey and to sleep in a strange hotel, awakened by a sudden spasm, sees with glad relief a streak of daylight showing under his door. Thank God, it is morning! The servants will be about in a minute: he can ring, and someone will come to look after him. The thought of being assuaged gives him strength to endure his pain. He is certain he heard footsteps: they come nearer, and then die away. The ray of light beneath his door is extinguished. It is midnight; someone has just turned down the gas; the last servant has gone to bed, and he must lie all night suffering without remedy.`,
  `I would fall asleep again, and thereafter would reawaken for short snatches only, just long enough to hear the regular creaking of the wainscot, or to open my eyes to stare at the shifting kaleidoscope of the darkness, to savour, in a momentary glimmer of consciousness, the sleep which lay heavy upon the furniture, the room, that whole of which I formed no more than a small part and whose insensibility I should very soon return to share. Or else while sleeping I had drifted back to an earlier stage in my life, now for ever outgrown, and had come under the thrall of one of my childish terrors, such as that old terror of my great-uncle’s pulling my curls which was effectually dispelled on the day—the dawn of a new era to me—when they were finally cropped from my head. I had forgotten that event during my sleep, but I remembered it again immediately I had succeeded in waking myself up to escape my great-uncle’s fingers, and as a measure of precaution I would bury the whole of my head in the pillow before returning to the world of dreams.`,
  `Sometimes, too, as Eve was created from a rib of Adam, a woman would be born during my sleep from some misplacing of my thigh. Conceived from the pleasure I was on the point of enjoying, she it was, I imagined, who offered me that pleasure. My body, conscious that its own warmth was permeating hers, would strive to become one with her, and I would awake. The rest of humanity seemed very remote in comparison with this woman whose company I had left but a moment ago; my cheek was still warm from her kiss, my body ached beneath the weight of hers. If, as would sometimes happen, she had the features of some woman whom I had known in waking hours, I would abandon myself altogether to this end: to find her again, like people who set out on a journey to see with their eyes some city of their desire, and imagine that one can taste in reality what has charmed one’s fancy. And then, gradually, the memory of her would fade away, I had forgotten the girl of my dream.`,
];

export const maxChars = allText.length;
export const maxParags = paragraphs.length;
